# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-18 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoorHouseDataForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('past_village_identifier', models.CharField(blank=True, db_column='past_village_identifier', max_length=30)),
                ('now_village_identifier', models.CharField(blank=True, db_column='now_village_identifier', max_length=30)),
                ('house_identifier', models.CharField(blank=True, db_column='now_house_identifier', max_length=30)),
                ('householder_identifier', models.CharField(blank=True, db_column='householder_identifier', max_length=30)),
                ('householder_name', models.CharField(blank=True, db_column='householder_name', max_length=30)),
                ('offpoverty_situation', models.CharField(blank=True, db_column='offpoverty_situation', max_length=20)),
                ('family_number', models.CharField(blank=True, db_column='family_number', max_length=10)),
                ('first_identify', models.CharField(blank=True, db_column='first_identify', max_length=50)),
                ('poverty_attribute', models.CharField(blank=True, db_column='poverty_attribute', max_length=30)),
                ('poor_reason', models.CharField(blank=True, db_column='poor_reason', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PoorPeopleDataForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house_identifier', models.CharField(blank=True, db_column='house_identifier', max_length=30)),
                ('people_identifier', models.CharField(blank=True, db_column='people_identifier', max_length=30)),
                ('people_name', models.CharField(blank=True, db_column='people_name', max_length=30)),
                ('people_relationship', models.CharField(blank=True, db_column='people_relationship', max_length=20)),
                ('card_type', models.CharField(blank=True, db_column='card_type', max_length=50)),
                ('card_number', models.CharField(blank=True, db_column='card_number', max_length=50)),
                ('birth_date', models.CharField(blank=True, db_column='birth_date', max_length=30)),
                ('is_student', models.CharField(blank=True, db_column='is_student', max_length=10)),
                ('is_minimum', models.CharField(blank=True, db_column='is_minimum', max_length=20)),
                ('health_situation', models.CharField(blank=True, db_column='health_situation', max_length=100)),
                ('first_identify', models.CharField(blank=True, db_column='first_identify', max_length=50)),
                ('poor_reason', models.CharField(blank=True, db_column='poor_reason', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_development_direction',
            field=models.CharField(blank=True, db_column='now_development_direction', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_dimension',
            field=models.CharField(blank=True, db_column='now_dimension', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_longitude',
            field=models.CharField(blank=True, db_column='now_longitude', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_party_member',
            field=models.CharField(blank=True, db_column='now_party_member', max_length=10),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_responsible_person',
            field=models.CharField(blank=True, db_column='now_responsible_person', max_length=100),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_telephone_number',
            field=models.CharField(blank=True, db_column='now_telephone_number', max_length=100),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_terrain_physiognomy',
            field=models.CharField(blank=True, db_column='now_terrain_physiognomy', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_village_identifier',
            field=models.CharField(blank=True, db_column='now_village_identifier', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_village_officer',
            field=models.CharField(blank=True, db_column='now_village_officer', max_length=10),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_development_direction',
            field=models.CharField(blank=True, db_column='past_development_direction', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_dimension',
            field=models.CharField(blank=True, db_column='past_dimension', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_home_number',
            field=models.CharField(blank=True, db_column='past_home_number', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_longitude',
            field=models.CharField(blank=True, db_column='past_longitude', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_party_member',
            field=models.CharField(blank=True, db_column='past_party_member', max_length=10),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_people_number',
            field=models.CharField(blank=True, db_column='past_people_number', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_poor_home',
            field=models.CharField(blank=True, db_column='past_poor_home', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_poor_people',
            field=models.CharField(blank=True, db_column='past_poor_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_responsible_person',
            field=models.CharField(blank=True, db_column='past_responsible_person', max_length=100),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_telephone_number',
            field=models.CharField(blank=True, db_column='past_telephone_number', max_length=100),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_terrain_physiognomy',
            field=models.CharField(blank=True, db_column='past_terrain_physiognomy', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_village_identifier',
            field=models.CharField(blank=True, db_column='past_village_identifier', max_length=30),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_village_officer',
            field=models.CharField(blank=True, db_column='past_village_officer', max_length=10),
        ),
    ]
