# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0002_auto_20180518_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorhousedataform',
            name='house_identifier',
            field=models.CharField(blank=True, db_column='house_identifier', max_length=30),
        ),
    ]
