# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-19 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0003_auto_20180519_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorhousedataform',
            name='householder_id',
            field=models.CharField(blank=True, db_column='householder_id', max_length=20),
        ),
    ]
