# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0004_poorhousedataform_householder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorhousedataform',
            name='year_date',
            field=models.CharField(blank=True, db_column='year_date', max_length=10),
        ),
    ]
