# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0005_poorhousedataform_year_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyStaticForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(blank=True, db_column='policy_number', max_length=30)),
                ('policy_first_layer', models.CharField(blank=True, db_column='policy_first_layer', max_length=100)),
                ('policy_second_layer', models.CharField(blank=True, db_column='policy_second_layer', max_length=100)),
                ('policy_third_layer', models.CharField(blank=True, db_column='policy_third_layer', max_length=100)),
                ('subsidy_one', models.CharField(blank=True, db_column='subsidy_one', max_length=500)),
                ('subsidy_two', models.CharField(blank=True, db_column='subsidy_two', max_length=500)),
                ('subsidy_three', models.CharField(blank=True, db_column='subsidy_three', max_length=500)),
                ('subsidy_limit', models.CharField(blank=True, db_column='subsidy_limit', max_length=500)),
                ('limit_condition', models.CharField(blank=True, db_column='limit_condition', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PoorHouseAdditionalForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house_identifier', models.CharField(blank=True, db_column='house_identifier', max_length=30)),
                ('policy_number', models.CharField(blank=True, db_column='policy_number', max_length=100)),
                ('policy_multiplier', models.CharField(blank=True, db_column='policy_multiplier', max_length=20)),
                ('plan_money', models.CharField(blank=True, db_column='plan_money', max_length=20)),
                ('fact_money', models.CharField(blank=True, db_column='fact_money', max_length=20)),
                ('date', models.CharField(blank=True, db_column='date', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='address',
            field=models.CharField(blank=True, db_column='address', max_length=100),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='address',
            field=models.CharField(blank=True, db_column='address', max_length=100),
        ),
    ]
