# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-24 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0007_poorpeopledataform_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='policystaticform',
            name='policy_object',
            field=models.CharField(blank=True, db_column='policy_object', max_length=50),
        ),
    ]
