# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-25 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0009_auto_20180524_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoorPeopleAdditionalForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house_identifier', models.CharField(blank=True, db_column='house_identifier', max_length=30)),
                ('people_identifier', models.CharField(blank=True, db_column='people_identifier', max_length=30)),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', max_length=50)),
                ('bank_number', models.CharField(blank=True, db_column='bank_number', max_length=50)),
                ('policy_number', models.CharField(blank=True, db_column='policy_number', max_length=30)),
                ('policy_multiplier', models.CharField(blank=True, db_column='policy_multiplier', max_length=20)),
                ('plan_money', models.CharField(blank=True, db_column='plan_money', max_length=20)),
                ('fact_money', models.CharField(blank=True, db_column='fact_money', max_length=20)),
                ('date', models.CharField(blank=True, db_column='date', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='poorhousedataform',
            name='offpoverty_situation',
        ),
        migrations.RemoveField(
            model_name='poorhousedataform',
            name='poverty_attribute',
        ),
        migrations.RemoveField(
            model_name='poorpeopledataform',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='poorpeopledataform',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='poorpeopledataform',
            name='is_student',
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_egression_people',
            field=models.CharField(blank=True, db_column='now_egression_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_five_home',
            field=models.CharField(blank=True, db_column='now_five_home', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_five_people',
            field=models.CharField(blank=True, db_column='now_five_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_handicapped_people',
            field=models.CharField(blank=True, db_column='now_handicapped_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_labor_people',
            field=models.CharField(blank=True, db_column='now_labor_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_minimum_home',
            field=models.CharField(blank=True, db_column='now_minimum_home', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_minimum_people',
            field=models.CharField(blank=True, db_column='now_minimum_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_nation_people',
            field=models.CharField(blank=True, db_column='now_nation_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_woman_people',
            field=models.CharField(blank=True, db_column='now_woman_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_egression_people',
            field=models.CharField(blank=True, db_column='past_egression_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_five_home',
            field=models.CharField(blank=True, db_column='past_five_home', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_five_people',
            field=models.CharField(blank=True, db_column='past_five_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_handicapped_people',
            field=models.CharField(blank=True, db_column='past_handicapped_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_labor_people',
            field=models.CharField(blank=True, db_column='past_labor_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_minimum_home',
            field=models.CharField(blank=True, db_column='past_minimum_home', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_minimum_people',
            field=models.CharField(blank=True, db_column='past_minimum_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_nation_people',
            field=models.CharField(blank=True, db_column='past_nation_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_woman_people',
            field=models.CharField(blank=True, db_column='past_woman_people', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='year_date',
            field=models.CharField(blank=True, db_column='year_date', max_length=10),
        ),
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='bank_name',
            field=models.CharField(blank=True, db_column='bank_name', max_length=50),
        ),
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='bank_number',
            field=models.CharField(blank=True, db_column='bank_number', max_length=50),
        ),
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='card_people',
            field=models.CharField(blank=True, db_column='card_people', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='now_village_identifier',
            field=models.CharField(blank=True, db_column='now_village_identifier', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='past_village_identifier',
            field=models.CharField(blank=True, db_column='past_village_identifier', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='people_id',
            field=models.CharField(blank=True, db_column='people_id', max_length=20),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='average_income',
            field=models.CharField(blank=True, db_column='average_income', max_length=20),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='danger_house',
            field=models.CharField(blank=True, db_column='danger_house', max_length=10),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='education_degree',
            field=models.CharField(blank=True, db_column='education_degree', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='health_situation',
            field=models.CharField(blank=True, db_column='health_situation', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='is_minimum',
            field=models.CharField(blank=True, db_column='is_minimum', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='join_medical',
            field=models.CharField(blank=True, db_column='join_medical', max_length=10),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='labor_ability',
            field=models.CharField(blank=True, db_column='labor_ability', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='offpoor_attribute',
            field=models.CharField(blank=True, db_column='offpoor_attribute', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='offpoor_year',
            field=models.CharField(blank=True, db_column='offpoor_year', max_length=20),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='people_nation',
            field=models.CharField(blank=True, db_column='people_nation', max_length=20),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='poor_attribute',
            field=models.CharField(blank=True, db_column='poor_attribute', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='school_situation',
            field=models.CharField(blank=True, db_column='school_situation', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='telephone',
            field=models.CharField(blank=True, db_column='telephone', max_length=20),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='water_hard',
            field=models.CharField(blank=True, db_column='water_hard', max_length=10),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='water_safe',
            field=models.CharField(blank=True, db_column='water_safe', max_length=10),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='work_situation',
            field=models.CharField(blank=True, db_column='work_situation', max_length=30),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='work_time',
            field=models.CharField(blank=True, db_column='work_time', max_length=10),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='education_degree',
            field=models.CharField(blank=True, db_column='education_degree', max_length=30),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='family_number',
            field=models.CharField(blank=True, db_column='family_number', max_length=10),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='join_medical',
            field=models.CharField(blank=True, db_column='join_medical', max_length=10),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='labor_ability',
            field=models.CharField(blank=True, db_column='labor_ability', max_length=30),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='offpoor_attribute',
            field=models.CharField(blank=True, db_column='offpoor_attribute', max_length=30),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='people_id',
            field=models.CharField(blank=True, db_column='people_id', max_length=20),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='people_nation',
            field=models.CharField(blank=True, db_column='people_nation', max_length=20),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='school_situation',
            field=models.CharField(blank=True, db_column='school_situation', max_length=30),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='work_time',
            field=models.CharField(blank=True, db_column='work_time', max_length=10),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='year_date',
            field=models.CharField(blank=True, db_column='year_date', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrativevillagedataform',
            name='now_party_member',
            field=models.CharField(blank=True, db_column='now_party_member', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativevillagedataform',
            name='now_village_officer',
            field=models.CharField(blank=True, db_column='now_village_officer', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativevillagedataform',
            name='past_party_member',
            field=models.CharField(blank=True, db_column='past_party_member', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrativevillagedataform',
            name='past_village_officer',
            field=models.CharField(blank=True, db_column='past_village_officer', max_length=20),
        ),
        migrations.AlterField(
            model_name='policystaticform',
            name='limit_condition',
            field=models.CharField(blank=True, db_column='limit_condition', max_length=200),
        ),
        migrations.AlterField(
            model_name='policystaticform',
            name='subsidy_limit',
            field=models.CharField(blank=True, db_column='subsidy_limit', max_length=100),
        ),
        migrations.AlterField(
            model_name='policystaticform',
            name='subsidy_one',
            field=models.CharField(blank=True, db_column='subsidy_one', max_length=100),
        ),
        migrations.AlterField(
            model_name='policystaticform',
            name='subsidy_three',
            field=models.CharField(blank=True, db_column='subsidy_three', max_length=100),
        ),
        migrations.AlterField(
            model_name='policystaticform',
            name='subsidy_two',
            field=models.CharField(blank=True, db_column='subsidy_two', max_length=100),
        ),
        migrations.AlterField(
            model_name='poorhouseadditionalform',
            name='policy_number',
            field=models.CharField(blank=True, db_column='policy_number', max_length=30),
        ),
        migrations.AlterField(
            model_name='poorhousedataform',
            name='poor_reason',
            field=models.CharField(blank=True, db_column='poor_reason', max_length=30),
        ),
        migrations.AlterField(
            model_name='poorpeopledataform',
            name='health_situation',
            field=models.CharField(blank=True, db_column='health_situation', max_length=30),
        ),
        migrations.AlterField(
            model_name='poorpeopledataform',
            name='is_minimum',
            field=models.CharField(blank=True, db_column='is_minimum', max_length=30),
        ),
        migrations.AlterField(
            model_name='poorpeopledataform',
            name='poor_reason',
            field=models.CharField(blank=True, db_column='poor_reason', max_length=30),
        ),
    ]
