# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-26 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0010_auto_20180525_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeVillageAdditionalForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('past_village_identifier', models.CharField(blank=True, db_column='past_village_identifier', max_length=30)),
                ('now_village_identifier', models.CharField(blank=True, db_column='now_village_identifier', max_length=30)),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', max_length=50)),
                ('bank_number', models.CharField(blank=True, db_column='bank_number', max_length=50)),
                ('card_people', models.CharField(blank=True, db_column='card_people', max_length=30)),
                ('people_id', models.CharField(blank=True, db_column='people_id', max_length=20)),
                ('policy_number', models.CharField(blank=True, db_column='policy_number', max_length=30)),
                ('policy_multiplier', models.CharField(blank=True, db_column='policy_multiplier', max_length=20)),
                ('plan_money', models.CharField(blank=True, db_column='plan_money', max_length=20)),
                ('fact_money', models.CharField(blank=True, db_column='fact_money', max_length=20)),
                ('date', models.CharField(blank=True, db_column='date', max_length=50)),
            ],
        ),
    ]
