# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-27 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0011_administrativevillageadditionalform'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_help_people',
            field=models.CharField(blank=True, db_column='now_help_people', max_length=50),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_help_unit',
            field=models.CharField(blank=True, db_column='now_help_unit', max_length=50),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_help_way',
            field=models.CharField(blank=True, db_column='now_help_way', max_length=50),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_help_people',
            field=models.CharField(blank=True, db_column='past_help_people', max_length=50),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_help_unit',
            field=models.CharField(blank=True, db_column='past_help_unit', max_length=50),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_help_way',
            field=models.CharField(blank=True, db_column='past_help_way', max_length=50),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='help_people',
            field=models.CharField(blank=True, db_column='help_people', max_length=50),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='help_unit',
            field=models.CharField(blank=True, db_column='help_unit', max_length=50),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='help_way',
            field=models.CharField(blank=True, db_column='help_way', max_length=50),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='help_people',
            field=models.CharField(blank=True, db_column='help_people', max_length=50),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='help_unit',
            field=models.CharField(blank=True, db_column='help_unit', max_length=50),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='help_way',
            field=models.CharField(blank=True, db_column='help_way', max_length=50),
        ),
    ]
