# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0012_auto_20180527_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='special_tag',
            field=models.CharField(blank=True, db_column='special_tag', max_length=10),
        ),
    ]
