# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0013_administrativevillagedataform_special_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperDataForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(blank=True, db_column='unit_name', max_length=50)),
                ('helper_name', models.CharField(blank=True, db_column='helper_name', max_length=30)),
                ('helper_sex', models.CharField(blank=True, db_column='helper_sex', max_length=10)),
                ('helper_post', models.CharField(blank=True, db_column='helper_post', max_length=50)),
                ('helper_type', models.CharField(blank=True, db_column='helper_type', max_length=30)),
                ('poor_town', models.CharField(blank=True, db_column='poor_town', max_length=50)),
                ('past_administrative_village', models.CharField(blank=True, db_column='past_administrative_village', max_length=50)),
                ('now_administrative_village', models.CharField(blank=True, db_column='now_administrative_village', max_length=50)),
                ('past_village_identifier', models.CharField(blank=True, db_column='past_village_identifier', max_length=30)),
                ('now_village_identifier', models.CharField(blank=True, db_column='now_village_identifier', max_length=30)),
                ('poor_home', models.CharField(blank=True, db_column='poor_home', max_length=20)),
                ('poor_name', models.CharField(blank=True, db_column='poor_name', max_length=30)),
                ('poor_group', models.CharField(blank=True, db_column='poor_group', max_length=20)),
                ('household_identifier', models.CharField(blank=True, db_column='household_identifier', max_length=20)),
                ('office_phone', models.CharField(blank=True, db_column='office_phone', max_length=100)),
                ('mobile_phone', models.CharField(blank=True, db_column='mobile_phone', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='house_group',
            field=models.CharField(blank=True, db_column='house_group', max_length=20),
        ),
    ]
