# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-31 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0014_auto_20180530_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativevillagedataform',
            name='special_tag',
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='town_tag',
            field=models.CharField(blank=True, db_column='town_tag', max_length=10),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='village_tag',
            field=models.CharField(blank=True, db_column='village_tag', max_length=10),
        ),
    ]
