# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0017_auto_20180605_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativevillageadditionalform',
            name='remarks',
            field=models.CharField(blank=True, db_column='remarks', max_length=300),
        ),
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='remarks',
            field=models.CharField(blank=True, db_column='remarks', max_length=300),
        ),
        migrations.AddField(
            model_name='poorpeopleadditionalform',
            name='remarks',
            field=models.CharField(blank=True, db_column='remarks', max_length=300),
        ),
    ]
