# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-10 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0018_auto_20180606_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorhousedataform',
            name='householder_id',
            field=models.CharField(blank=True, db_column='householder_id', db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='poorhousedataform',
            name='now_village_identifier',
            field=models.CharField(blank=True, db_column='now_village_identifier', db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='poorhousedataform',
            name='past_village_identifier',
            field=models.CharField(blank=True, db_column='past_village_identifier', db_index=True, max_length=30),
        ),
    ]
