# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0018_auto_20180606_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='now_help_phone',
            field=models.CharField(blank=True, db_column='now_help_phone', max_length=100),
        ),
        migrations.AddField(
            model_name='administrativevillagedataform',
            name='past_help_phone',
            field=models.CharField(blank=True, db_column='past_help_phone', max_length=100),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='help_phone',
            field=models.CharField(blank=True, db_column='help_phone', max_length=100),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='help_phone',
            field=models.CharField(blank=True, db_column='help_phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='administrativevillagedataform',
            name='town_tag',
            field=models.CharField(blank=True, db_column='town', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrativevillagedataform',
            name='village_tag',
            field=models.CharField(blank=True, db_column='village', max_length=10),
        ),
    ]
