# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-10 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0020_auto_20180610_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poorhousedataform',
            name='now_village_identifier',
            field=models.CharField(blank=True, db_column='now_village_identifier', db_index=True, max_length=30),
        ),
    ]
