# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-10 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0021_auto_20180610_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativevillagedataform',
            name='town_tag',
        ),
        migrations.RemoveField(
            model_name='administrativevillagedataform',
            name='village_tag',
        ),
    ]
