# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0023_auto_20180610_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperdataform',
            name='helper_tag',
            field=models.CharField(blank=True, db_column='helper_tag', max_length=5),
        ),
    ]
