# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0025_merge_20180613_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='policystaticform',
            name='implement_department',
            field=models.CharField(blank=True, db_column='implement_department', max_length=50),
        ),
    ]
