# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-14 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0027_auto_20180613_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='householder_id',
            field=models.CharField(blank=True, db_column='householder_id', max_length=20),
        ),
        migrations.AddField(
            model_name='poorpeopleadditionalform',
            name='people_id',
            field=models.CharField(blank=True, db_column='people_id', max_length=20),
        ),
    ]
