# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0028_auto_20180614_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poorhousedataform',
            name='is_minimum',
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='is_five',
            field=models.CharField(blank=True, db_column='is_five', max_length=30),
        ),
    ]
