# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0030_auto_20180617_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorpeopledataform',
            name='special_people',
            field=models.CharField(blank=True, db_column='special_people', max_length=50),
        ),
    ]
