# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0031_poorpeopledataform_special_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poorpeopledataform',
            name='is_minimum',
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='is_minimum',
            field=models.CharField(blank=True, db_column='is_minimum', max_length=30),
        ),
    ]
