# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-18 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0032_auto_20180618_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorpeopledataform',
            name='poor_attribute',
            field=models.CharField(blank=True, db_column='poor_attribute', max_length=30),
        ),
    ]
