# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0034_auto_20180826_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='householder_name',
            field=models.CharField(blank=True, db_column='householder_name', max_length=30),
        ),
        migrations.AddField(
            model_name='poorpeopleadditionalform',
            name='householder_id',
            field=models.CharField(blank=True, db_column='householder_id', max_length=20),
        ),
        migrations.AddField(
            model_name='poorpeopleadditionalform',
            name='people_name',
            field=models.CharField(blank=True, db_column='people_name', max_length=30),
        ),
    ]
