# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-15 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0035_auto_20180908_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativevillageadditionalform',
            name='subsidy_standard',
            field=models.CharField(blank=True, db_column='subsidy_standard', max_length=300),
        ),
        migrations.AddField(
            model_name='poorhouseadditionalform',
            name='subsidy_standard',
            field=models.CharField(blank=True, db_column='subsidy_standard', max_length=300),
        ),
        migrations.AddField(
            model_name='poorpeopleadditionalform',
            name='subsidy_standard',
            field=models.CharField(blank=True, db_column='subsidy_standard', max_length=300),
        ),
    ]
