# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-16 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0036_auto_20180915_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryAgritainmentDataForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('town_name', models.CharField(blank=True, db_column='town_name', max_length=50)),
                ('administrative_village', models.CharField(blank=True, db_column='administrative_village', max_length=50)),
                ('ascription_group', models.CharField(blank=True, db_column='ascription_group', max_length=20)),
                ('agritainment_name', models.CharField(blank=True, db_column='agritainment_name', max_length=100)),
                ('agritainment_holder', models.CharField(blank=True, db_column='agritainment_holder', max_length=30)),
                ('agritainment_id', models.CharField(blank=True, db_column='agritainment_id', max_length=20)),
                ('subsidy_standard', models.CharField(blank=True, db_column='subsidy_standard', max_length=300)),
                ('subsidy_multiplier', models.CharField(blank=True, db_column='subsidy_multiplier', max_length=20)),
                ('subsidy_limit', models.CharField(blank=True, db_column='subsidy_limit', max_length=100)),
                ('plan_subsidy', models.CharField(blank=True, db_column='plan_subsidy', max_length=100)),
                ('fact_subsidy', models.CharField(blank=True, db_column='fact_subsidy', max_length=100)),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', max_length=50)),
                ('bank_number', models.CharField(blank=True, db_column='bank_number', max_length=50)),
                ('receivables_name', models.CharField(blank=True, db_column='receivables_name', max_length=30)),
                ('receivables_id', models.CharField(blank=True, db_column='receivables_id', max_length=20)),
                ('grant_date', models.CharField(blank=True, db_column='grant_date', max_length=30)),
                ('remarks', models.CharField(blank=True, db_column='remarks', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryEnterpriseDataForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('town_name', models.CharField(blank=True, db_column='town_name', max_length=50)),
                ('administrative_village', models.CharField(blank=True, db_column='administrative_village', max_length=50)),
                ('ascription_group', models.CharField(blank=True, db_column='ascription_group', max_length=20)),
                ('enterprise_name', models.CharField(blank=True, db_column='enterprise_name', max_length=100)),
                ('management_address', models.CharField(blank=True, db_column='management_address', max_length=200)),
                ('institution_code', models.CharField(blank=True, db_column='institution_code', max_length=100)),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', max_length=50)),
                ('bank_number', models.CharField(blank=True, db_column='bank_number', max_length=50)),
                ('subsidy_name', models.CharField(blank=True, db_column='subsidy_name', max_length=200)),
                ('subsidy_standard', models.CharField(blank=True, db_column='subsidy_standard', max_length=300)),
                ('subsidy_multiplier', models.CharField(blank=True, db_column='subsidy_multiplier', max_length=20)),
                ('subsidy_limit', models.CharField(blank=True, db_column='subsidy_limit', max_length=100)),
                ('plan_subsidy', models.CharField(blank=True, db_column='plan_subsidy', max_length=100)),
                ('fact_subsidy', models.CharField(blank=True, db_column='fact_subsidy', max_length=100)),
                ('grant_date', models.CharField(blank=True, db_column='grant_date', max_length=30)),
                ('remarks', models.CharField(blank=True, db_column='remarks', max_length=300)),
            ],
        ),
    ]
