# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-21 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0037_industryagritainmentdataform_industryenterprisedataform'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorhousedataform',
            name='house_classification',
            field=models.CharField(blank=True, db_column='house_classification', max_length=100),
        ),
        migrations.AddField(
            model_name='poorhousedataform',
            name='remarks',
            field=models.CharField(blank=True, db_column='remarks', max_length=300),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='people_classification',
            field=models.CharField(blank=True, db_column='people_classification', max_length=100),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='remarks',
            field=models.CharField(blank=True, db_column='remarks', max_length=300),
        ),
    ]
