# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-24 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0038_auto_20180921_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='poorhousedataform',
            name='town_name',
            field=models.CharField(blank=True, db_column='town_name', max_length=50),
        ),
        migrations.AddField(
            model_name='poorpeopledataform',
            name='town_name',
            field=models.CharField(blank=True, db_column='town_name', max_length=50),
        ),
    ]
