# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0041_poorpeopledataform_poorhouse_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperdataform',
            name='helper_id',
            field=models.CharField(blank=True, db_column='helper_id', max_length=20),
        ),
    ]
