# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-13 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_form', '0042_helperdataform_helper_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryFinanceDataForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, db_column='bank_name', max_length=50)),
                ('management_name', models.CharField(blank=True, db_column='management_name', max_length=30)),
                ('management_id', models.CharField(blank=True, db_column='management_id', max_length=20)),
                ('town_name', models.CharField(blank=True, db_column='town_name', max_length=50)),
                ('administrative_village', models.CharField(blank=True, db_column='administrative_village', max_length=50)),
                ('home_number', models.CharField(blank=True, db_column='home_number', max_length=20)),
                ('loan_money', models.CharField(blank=True, db_column='loan_money', max_length=20)),
                ('loan_begin', models.CharField(blank=True, db_column='loan_begin', max_length=30)),
                ('loan_end', models.CharField(blank=True, db_column='loan_end', max_length=30)),
                ('remarks', models.CharField(blank=True, db_column='remarks', max_length=300)),
            ],
        ),
    ]
