# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-09 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.Department', verbose_name='所属部门'),
        ),
    ]
