# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0003_auto_20180630_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='openid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userextra',
            name='token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
