# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('url', models.URLField(default='#', verbose_name='url')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_common.Nav', verbose_name='上级导航')),
            ],
            options={
                'verbose_name_plural': '导航',
                'verbose_name': '导航',
            },
        ),
    ]
