# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='图标'),
        ),
    ]
