# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_nav_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='sort',
            field=models.SmallIntegerField(default='1', verbose_name='排序'),
        ),
    ]
