# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0004_nav_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annunciate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('attach_path', models.FileField(upload_to='attach/%Y/%m/%d', verbose_name='附件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentDecree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('attach_path', models.FileField(upload_to='attach/%Y/%m/%d', verbose_name='附件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
