# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_annunciate_governmentdecree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annunciate',
            name='attach_path',
            field=models.CharField(max_length=100, verbose_name='附件路径'),
        ),
        migrations.AlterField(
            model_name='governmentdecree',
            name='attach_path',
            field=models.CharField(max_length=100, verbose_name='附件路径'),
        ),
    ]
