# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_auto_20180613_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='操作时间')),
                ('user_id', models.IntegerField()),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='简介')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='详细')),
            ],
        ),
    ]
