# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-30 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0007_logs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annunciate',
            options={'verbose_name': '通告'},
        ),
        migrations.AlterModelOptions(
            name='governmentdecree',
            options={'verbose_name': '政令'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name': '日志'},
        ),
    ]
