# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-15 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0008_auto_20180630_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='反馈时间')),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=500, null=True, verbose_name='类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '意见反馈',
            },
        ),
    ]
