# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-19 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0009_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='img_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='图片路径'),
        ),
    ]
