# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-10 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0011_helpcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='about_object',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='about_object_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
