# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-10 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0012_auto_20180910_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='status',
            field=models.SmallIntegerField(default=2, verbose_name='状态'),
        ),
    ]
