# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-09-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0013_feedbacks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
