# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-15 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0002_auto_20180624_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourInOneAdditionalForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('people_id', models.CharField(blank=True, db_column='people_id', max_length=20)),
                ('people_name', models.CharField(blank=True, db_column='people_name', max_length=30)),
                ('people_address', models.CharField(blank=True, db_column='people_address', max_length=100)),
                ('bottom_property', models.CharField(blank=True, db_column='bottom_property', max_length=50)),
                ('institution_name', models.CharField(blank=True, db_column='institution_name', max_length=50)),
                ('medical_type', models.CharField(blank=True, db_column='medical_type', max_length=30)),
                ('people_diagnosis', models.CharField(blank=True, db_column='people_diagnosis', max_length=100)),
                ('in_time', models.CharField(blank=True, db_column='in_time', max_length=50)),
                ('off_time', models.CharField(blank=True, db_column='off_time', max_length=50)),
                ('medical_amount', models.CharField(blank=True, db_column='medical_amount', max_length=20)),
                ('inclusion_compensation', models.CharField(blank=True, db_column='inclusion_compensation', max_length=20)),
                ('overall_payment', models.CharField(blank=True, db_column='overall_payment', max_length=20)),
                ('medical_compensation', models.CharField(blank=True, db_column='medical_compensation', max_length=20)),
                ('insurance_indemnity', models.CharField(blank=True, db_column='insurance_indemnity', max_length=20)),
                ('civil_rescue', models.CharField(blank=True, db_column='civil_rescue', max_length=20)),
                ('supplement_indemnity', models.CharField(blank=True, db_column='supplement_indemnity', max_length=20)),
                ('people_payment', models.CharField(blank=True, db_column='people_payment', max_length=20)),
                ('settlement_date', models.CharField(blank=True, db_column='settlement_date', max_length=30)),
            ],
        ),
    ]
