# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='上传时间')),
                ('approve_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='审批时间')),
                ('user_id', models.IntegerField()),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
            ],
            options={
                'verbose_name': 'excel审批',
            },
        ),
    ]
