# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-29 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelapprove',
            name='approve_time',
            field=models.DateTimeField(null=True, verbose_name='审批时间'),
        ),
    ]
