# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-29 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_view', '0002_auto_20180729_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelapprove',
            name='upload_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excelapprove',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
