# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-07-29 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_view', '0004_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='标题'),
        ),
    ]
