# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-02 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_view', '0005_template_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelapprove',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
