# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-08-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_view', '0006_excelapprove_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='policy_object',
            field=models.CharField(blank=True, db_column='policy_object', default='', max_length=10),
        ),
    ]
